version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d/
      - ./docker/mysql/sql/sqlike:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: sqlike
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  mysql_sakila:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d/
      - ./docker/mysql/sql/sakila:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 13306:3306
